### ISSUE TITLE
Submit some change to StSav012 adblockrules.

### ISSUE THREAD

**Issue by smed79** [StSav012/adblockrules#1]
Hi, 
i have made some change to speed up your liste and make it easily readable.
`http://pastie.org/pastes/10428090/text?key=vtiibzcshujkooyqroop5g`

**Element Hiding Helper pour Adblock Plus** can help you to easily creat filter.
https://adblockplus.org/elemhidehelper

Note that officiel lists are recommended: 
- http://adblockplus.org/en/subscriptions
- https://www.fanboy.co.nz/

Regards,
Med

**Comment by StSav012** [comment]
Thank you but your assumption about || is not always correct. I try to block the site itself, without bothering what part of it (say, a sub-site; I can't recall how it's called really) sends ad.
As for the prefabricated lists, they're much larger than mine, and therefore they work several times slower according to Chromium's timeline tool.
And I'd rather prevent an ad from appearing by blocking a site than load it and hide it then.
I really appreciate your attention. Thanks again.

**Comment by smed79** [comment]
Please ask the adblockers developers if a large list of filters impact the performance? 
I'm not sure but i think NO!

good luck :) 
Med
