### ISSUE TITLE
Feature Request: Hide posts with reposts

### ISSUE THREAD

**Issue by Devocub** [StSav012/adblockrules#2]
Некоторые паблики постят нормальные контент, а посты с репостами - реклама. Возможность скрывать посты с репостами. (для определённых пабликов)

**Comment by StSav012** [comment]
Доброе утро понедельника!
Это, несомненно, можно прописать в списке правил. Покажите, пожалуйста, пример такого репоста — я добавлю пример соответствующего правила. Спасибо!

**Comment by Devocub** [comment]
Любой репост, который делает паблик себе на стену

**Comment by StSav012** [comment]
Сделано в [5ddc1ad](https://github.com/StSav012/adblockrules/commit/5ddc1adc14dfb0e51515819a8994bd9603664e5a). В качестве примера написана одна группа в массиве `banned_reposts_from`.
Спасибо за предложение!
