### ISSUE TITLE
Doesn't  work for rp5.by

### ISSUE THREAD

**Issue by Siarhei-Yarkavy** [StSav012/adblockrules#5]
Doesn't work for rp5.by but works for rp5.ru
window10, tampermonkey, firefox 67 beta

**Comment by StSav012** [comment]
Hello! Are you sure what site it works on? I can't see the difference?

**Comment by Siarhei-Yarkavy** [comment]
Sorry, I updated my comment, it doesn't work for rp5.by but works for rp5.ru

**Comment by StSav012** [comment]
All right. I will see what I can do tomorrow. Thanks.

**Comment by StSav012** [comment]
For some reason, rp5.by does not redirect to HTTPS. The script matches updated.
